name: Frontend Code Quality

on:
  push:
    branches:
      - '**'  # This matches all branches
  pull_request:
    branches:
      - '**'  # This matches all branches

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check TypeScript
        run: bun run type-check

      - name: Run ESLint
        run: bun run lint:check

      - name: Check formatting
        run: bun run format:check
      
      - name: Build frontend
        run: bun run build

