name: Tauri Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
                libwebkit2gtk-4.1-dev \
                build-essential \
                curl \
                wget \
                file \
                libxdo-dev \
                libssl-dev \
                libayatana-appindicator3-dev \
                librsvg2-dev \
                libgtk-3-dev \
                patchelf

      - name: Install frontend dependencies
        run: bun install
        
      - name: Check Rust formatting
        working-directory: src-tauri
        run: cargo fmt --check
        
      - name: Run clippy
        working-directory: src-tauri
        run: cargo clippy -- -D warnings
        
      - name: Build Tauri app
        run: bun tauri build
        
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: src-tauri/target/release/bundle/deb/*.deb
