name: Tauri Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libgtk-3-dev \
            patchelf \
            nsis \
            lld \
            llvm \
            rpm \
            fakeroot \
            libwebkit2gtk-4.1-0=2.44.0-2 \
            libwebkit2gtk-4.1-dev=2.44.0-2 \
            libjavascriptcoregtk-4.1-0=2.44.0-2 \
            libjavascriptcoregtk-4.1-dev=2.44.0-2 \
            gir1.2-javascriptcoregtk-4.1=2.44.0-2 \
            gir1.2-webkit2-4.1=2.44.0-2

      - name: Install frontend dependencies
        run: bun install
        
      - name: Check Rust formatting
        working-directory: src-tauri
        run: cargo fmt --check
        
      - name: Run clippy
        working-directory: src-tauri
        run: cargo clippy -- -D warnings

      - name: Setup Windows cross-compilation
        run: |
          rustup target add x86_64-pc-windows-msvc
          cargo install --locked cargo-xwin

      - name: Build Tauri app (Linux)
        run: bun tauri build

      - name: Upload Linux DEB
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: src-tauri/target/release/bundle/deb/*.deb

      - name: Upload Linux RPM
        uses: actions/upload-artifact@v4
        with:
          name: linux-rpm
          path: src-tauri/target/release/bundle/rpm/*.rpm

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage

      - name: Build Tauri app (Windows)
        run: bun tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc

      - name: Upload Windows NSIS Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: src-tauri/target/x86_64-pc-windows-msvc/release/app.exe
